services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    hostname: jellyfin
    volumes:
      - ./media:/media
    environment:
      - JELLYFIN_PublishedServerUrl=10.66.66.1
    extra_hosts:
      - 'host.docker.internal:host-gateway'
